### PR TITLE
makes compatible with others drivers that uses SonarBeam structure

### PR DESCRIPTION
**Pull request by romulogcerqueira**

### CODE REVIEW

**Comment by doudou** [comment]
Do NOT remove a port on a component like that. Add a new port, with the new name, and push the data on both.

**Comment by doudou** [comment]
OK ... I won't merge this on master and we can't keep this fork around forever... Why was the change made in the first place again ?

**Comment by romulogcerqueira** [comment]
Just to make it clear: Undo this change and open a pull request with your suggestions directly to Rock drivers?

**Comment by doudou** [comment]
> Just to make it clear: Undo this change and open a pull request with your suggestions directly to Rock drivers?

My understanding is that the name change was there to help the creation of a UI.

What about creating a new port with the new name, but also with the new sonar data structure ? Wouldn't that be the best option ? If yes, then the best would be to do the change and create a PR against rock-drivers

**Comment by romulogcerqueira** [comment]
I agree with you. I will do the changes and open a PR against rock-drivers soon.

**Pull request merged**
